#!/usr/bin/env Rscript

# 20180501 -- time series concatinated ICA for 83 voxels
# + voxel x voxel correlation of average (accross subject) ts
# -> probably not used. instead look at fsl's melodic for ICA
#
# input ts generated by 
#  scripts/04_GP_parcellation_get_timeseries.bash
#
# N.B see check_orders.R to confirm voxel order

#devtools::install_github('LabNeuroCogDevel/LNCDR')
#install.packages('fastICA')

###################
### read in mask
###################
# get index of mask
mask.file <- "/Volumes/Phillips/P5/DUP/seed_fc/GP_seeds_fromAtlas_FINAL/LGP.nii.gz"
mask_nii <- oro.nifti::readNIfTI(mask.file)
vx_ijk <- which(mask_nii@.Data!=0,arr.ind=T)
colnames(vx_ijk) <- c('i','j','k')
# order like afni: z, y, -x :: AFNI does RPI, we have LPI
vx_afni <- vx_ijk[order(vx_ijk[,3],vx_ijk[,2],-vx_ijk[,1]),]
# see check_orders.R (enum.nii.gz) to verify this is correct


###################
### read in 1d files, arrange data
###################
# function to read in file or return NULL
readfile <- function(f)  tryCatch( read.table(f), error=function(e) NULL)
# list all files
files <- Sys.glob("subjs/*/*_LGP_voxelwise_ts_noAvg.1d")
# read in all files (NULL if error)
allvalues <- lapply(files, FUN=readfile)
# assign name to each element of list
names(allvalues) <-  gsub(".*(\\d{5}_\\d{8}).*", "\\1", files)

# remove missing (LGP: 21: 11423_20140916)
allvalues <- allvalues[! sapply(allvalues, is.null) ]

# make into 3d matrix
# time x voxel x subject => 300 x 83 x 46
m <- unlist(allvalues)
dim(m) <- c(dim(allvalues[[1]]), length(allvalues))
# check: time,roi,subject dims match
stopifnot( allvalues[[43]][24, 5] ==  m[24, 5, 43] )

# put a name on the dimensions (count)
n <- as.list(dim(m))
names(n) <- c("tr","roi","subj")



###################
### do calculations
###################

## ICA on concatated timeseries
# concat all subjects together
# change dim order
m_2d <- aperm(m, c(1,3,2))
dim(m_2d) <-c(n$tr*n$subj,n$roi) # 46*300 x 83
# tr 1 of roi 24 of 43rd subject matches
stopifnot( m_2d[(43-1)*n$tr + 1, 24] == m[1,24,43] )

# get ICs from concanated timeseries
nica <- 2
ica_concat <- fastICA::fastICA(m_2d,n.comp=nica)
# ica_concat$K has the 2 components

## correlation, not used
# roi x roi, ts per subj
cor_vox_all <- apply(m, 3, cor) # 83^2 x 46 
dim(cor_vox_all) <- c(n$roi,n$roi,n$subj) # 83 x 83 x 46
# check: corr between roi 24 and roi 5 of subj 43 is .77
stopifnot( cor_vox_all[24,5,43] == cor(m[,24,43],m[,5,43]) ) # 0.7762524

##################
### add to nifti
#################
# put voxels and ics into a dataframe
data_to_nii <- as.data.frame(cbind(vx_afni,ica_concat$K))
# and name the columns
colnames(data_to_nii)[3 + 1:nica] <- paste0('ica',1:nica) 
#   i  j  k         ica1          ica2
#  49 57 31 -0.001553223 -0.0009229661
#  48 57 31 -0.001499570  0.0002406886
#  ....

## write out
# mask is int, but we want more percsion, change type
datatype(mask_nii) <- 16; bitpix(mask_nii) <- 32
# save output as ica_concat_ica{1,2}.nii.gz
LNCDR::to_nii(mask_nii,data_to_nii,'ica_concat_ica1','ica1')
LNCDR::to_nii(mask_nii,data_to_nii,'ica_concat_ica2','ica2')
# TODO: add more lines for more ICs

###################
### MEANS
###################

# sum across all subjects: time x voxel => 300 x 83
mean_xsubj <- apply(m, MARGIN=c(1, 2), mean)
stopifnot( mean_xsubj[24, 5] == mean(m[24, 5, ]) )

# vox by vox correlation
cor_vox <- cor(mean_xsubj) # 83 x 83
stopifnot( cor_vox[24, 3] == cor(mean_xsubj[, 24], mean_xsubj[, 3]) )

# look at it
image(cor_vox)   # raw values
heatmap(cor_vox) # dendrogram

