#!/usr/bin/env bash

file="$1"; shift
contrast="$1";shift
p="$1"; shift
[ -z  "$file" -o ! -r "$file" ] && echo "cannot read file '$file'" && exit 1
[ -z "$contrast" ] && echo "bricknum: " && read contrast;
[ -z "$p" ] && echo "p-vale: 0." && read p && p="0.$p"

sb=$(3dinfo -label2index ${contrast}_GLT#0_Coef  $file)
tsb=$(3dinfo -label2index ${contrast}_GLT#0_Tstat  $file)
[ -z "$sb"  ] && echo "ERROR: no brik like ${contrast}_GLT#0_Coef" && exit 1
[ -z "$tsb" ] && echo "ERROR: no brik like ${contrast}_GLT#0_Tstat" && exit 1

#useage: drive_afni_stat 64 0.05
# $1: input brick
# $2: p-value
# $3: range
# $4: numcol

set -x
plugout_drive -quit -com "SET_SUBBRICKS -1 $sb $tsb" \
                    -com "SET_THRESHNEW A $p *p" 
