#!/usr/bin/env bash
# START AFNI: should check socket instead of pid
# osx needs a pidof
function pidof {
  ps axc|awk "{if (\$5==\"$1\") print \$1}"|tr ' ' '\n' |sed 1q
}
afnipid=$(pidof afni)
lastpid=$(cat .afnipid)
if [[ -z "$afnipid" || ! -r .afnipid || $lastpid -ne $afnipid ]]; then
   afni -YESplugouts -niml  -dset $@ &
   sleep 20;
   pidof afni > .afnipid
else 
   echo "using afni@$(cat .afnipid)"
fi

